name: Build Transfer

on:
  workflow_call:
    inputs:
      dry-run:
        description: "An indication of whether to commit/publish results"
        required: true
        type: string
      is-dependabot:
        description: "An indication of a dependabot pull request"
        required: true
        type: string

jobs:
  build-api:
    name: Build Transfer.API
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x

      - uses: ./.github/actions/dotnet-build
        with:
          solution: Transfer.sln
          project: domains/transfer/Transfer.API/API/API.csproj
          configuration: domains/transfer/Transfer.API/configuration.yaml
          dry-run: ${{ inputs.dry-run }}

  build-claim-automation:
    name: Build ClaimAutomation.Worker
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x

      - uses: ./.github/actions/dotnet-build
        with:
          solution: Transfer.sln
          project: domains/transfer/ClaimAutomation/Worker/Worker.csproj
          configuration: domains/transfer/ClaimAutomation/configuration.yaml
          dry-run: ${{ inputs.dry-run }}

  build-transfer-automation:
    name: Build TransferAutomation.Worker
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup dotnet
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: 9.0.x

      - uses: ./.github/actions/dotnet-build
        with:
          solution: Transfer.sln
          project: domains/transfer/TransferAgreementAutomation/Worker/Worker.csproj
          configuration: domains/transfer/TransferAgreementAutomation/configuration.yaml
          dry-run: ${{ inputs.dry-run }}
